build:
  version: "1.1"

cards:
  message: "Welcome to Loans service related Prod APIs "
  contactDetails:
    name: "Johnson Lech - Product Owner"
    email: "johnson@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932