#spring.application.name=ConfigServer

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Suvendu-hatua/banking-microservice-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

#        native:
#          search-locations: "classpath:/config"


#server - port setting
server:
  port: 8071



